---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-gitps
  name: test-gitps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-gitps
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-gitps
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-gitps
  name: test-gitops-svc
  #namespace: test-gitops-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-gitps
  type: LoadBalancer
status:
  loadBalancer: {}
